### ISSUE TITLE
[gocon2022s] Remo の miro ページに codelab リンクや画像などを設置する

### ISSUE THREAD

**Issue by mi-bear** [WomenWhoGoTokyo/codelab#102]
https://goconjp.slack.com/archives/C021JGN0L67/p1647756243587699?thread_ts=1647167131.824659&cid=C021JGN0L67

**Comment by mom0tomo** [comment]
- [x] 画像をつくる
- [x] 当日用のペライチページを作る
  - https://womenwhogotokyo.github.io/goconference2022_spring/
- [x] リンクを貼る（yagipyさんに依頼済み)
